### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by kgryte** [math-io/float32-normalize#1]

**Comment by Planeshifter** [comment]
Look all sound to me. One question: Would it make sense to document what happens when one calls the function with a `float64` number, namely that the result will be off and not satisfy `x = y * 2^exp`?

**Comment by kgryte** [comment]
ATM the `README` states 

> The `function` expects a finite, non-zero single-precision floating-point number `x`.

 and the examples use `float64-to-float32` when a `float32` could differ from `float64`. Currently, that results could differ if provided a `float64` is implied. Do you feel this needs to be made more explicit?

**Comment by Planeshifter** [comment]
My thought has been that one might warn the user that the function accepts numbers of any type and will only fail silently instead of throwing. But maybe not necessary to make this more explicit.

**Comment by kgryte** [comment]
Yeah, the key line is [L36](https://github.com/math-io/float32-normalize/blob/2c26717c9ba7688119021377d496d89eedfa8706/lib/index.js#L36).

If we assumed that a compiler would only promote the scalar to `float32` and that the result of `(float32) x (float32)` is a `float32`, then the `toFloat32` operation is not necessary.

If the `toFloat32` operation is removed and value types are preserved, then the relation holds regardless of what input type is provided.

However, if the compiler promotes the result of multiplication to `float64`, then the relation may no longer hold.

At the moment, the stance is "on the user to ensure a `float32` is provided and the implementation will make 'sure' that a `float32` is returned." Obviously, this stance is not without its pitfalls.

**Comment by Planeshifter** [comment]
Maybe this information could be added as a note to the README.md file? 
But if you don't deem it necessary, please go ahead and publish.
